---
- name: Configure uplinks from ESXi host
  hosts: apics
  connection: local
  gather_facts: no
  vars_files:
    - ./vars/configure_uplinks_vars.yml
    - ./credentials/aci_credentials.yml


  tasks:

    - name: Get available leaf switch pairs
      #GET {{apic}}/node/class/fabricNodePEp.json
      aci_switch_policy_vpc_protection_group:
        host: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        state: query
      register: query_result
