---
- name: Configure uplinks from ESXi host
  hosts: apics
  connection: local
  gather_facts: no
  vars_files:
    - ./vars/configure_uplinks_vars.yml

  tasks:

    - name: Get available leaf switch pairs
      #GET {{apic}}/node/class/fabricNodePEp.json
      aci_switch_policy_vpc_protection_group:
        host: apic
        username: admin
        password: SomeSecretPassword
        state: query
      register: query_result
