---

#Acceptable values are: ada_prod, ada_preprod, southbelt_prod, southbelt_preprod, aits_prod, aits_preprod
#choice would determine the {{apic}} variable which would actually be shorthand for "https://{{inventory_host}}/api"
apic: ada_prod

#Acceptable values are: vmkernel_bundled, vmkernel_unbundled, vmguest_bundled, vmguest_unbundled
use_case: vmkernel_bundled

#APIC Login Credentials
aci_username: "{{ vaulted_aci_username }}"
aci_password: "{{ vaulted_aci_password }}"
